{
  "errorpharse": {
    "data": {
      "1": {
        "en": "Error 1",
        "th": "ตาย 1"
      },
      "2": {
        "en": "Error 2",
        "th": "ตาย 2"
      },
      "3": {
        "en": "Error 3",
        "th": "ตาย 3"
      }
    }
  }
}
